### ISSUE TITLE
Keybinding to stop gtk-recordmydesktop/ffmpeg?

### ISSUE THREAD

**Issue by crydalch** [rjanja/desktop-capture#32]
I love this applet! I'm always needing to take screenshots and grab video snippets! Thank you for combining screenshots and recordings into one applet!

One of the few things I wish is a keybinding to stop a recording with recordmydesktop. Would that be possible? Or perhaps, make it so we could Ctrl+Click the applet icon, to stop any running recordings? I understand it's not possible for the cinnamon-recorder, but if any other format is detected, could that hotkey run the 'stop recording' command?

Thanks!

**Comment by rjanja** [comment]
Hi, thanks for the feedback. I've gone ahead and added in a custom keybinding for stopping the current recording. It'll be at the bottom of the settings. If the cinnamon recorder is used it will toggle start/stopping recording. For other recorders like RecordMyDesktop and FFmpeg, because there may be multiple recording options, it doesn't try to choose one to start. I'll revisit this later because it's not as intuitive as I'd like.

![screenshot-area-2015-01-01-140043](https://cloud.githubusercontent.com/assets/164802/5593382/a66b2e52-91be-11e4-85b3-ee0dcbcbb052.png)

The latest update is 1.01 and available on Spices or direct from Github. Let me know if you have any problems with it! Cheers!

**Comment by crydalch** [comment]
This is great, and works perfectly! Thanks so much!
