### ISSUE TITLE
Green Information Box too small and "generic" type in settings-schema

### ISSUE THREAD

**Issue by NikoKrause** [rjanja/desktop-capture#54]
Hey, while translating your applet I noticed a few things:

1. After pressing "Area", a green information box appears with informations about how taking screenshots. The box is too small. The last string says: "Press ENTER or KP_RETURN to complete the capture, or ..." It misses "or ESC to cancel". This gets worse with German translation, because Strings in German are longer.

2. You have "type": "generic" in settings-schema. Those aren't shown in the settings of the applet. What are they good for?

3. I don't understand the following settings:
"Include applied styles in UI capture"
"Whether to include CSS selection styles in Cinnamon UI screenshots"
"Last selected page (tab index) of settings application"
"Capture window as area (suggested, or shots may be black or distorted)"
"Whether to use area selection for window captures"
"Last selected sub-page (tab index) of settings application"
This means, I couldn't figure out, what they are doing. I see no difference. Therefore it's hard to translate them.

4. Tooltip of the button "Click here to send an example notification" doesn't work.

EDIT:
5. There's a big gap in the menu, which is even bigger in the german version:
![screenshot-cinnamon-2017-01-05-020820](https://cloud.githubusercontent.com/assets/8415124/21665356/65914724-d2ec-11e6-8b26-0535db2b2be2.png)
![screenshot-cinnamon-2017-01-05-020744](https://cloud.githubusercontent.com/assets/8415124/21665357/67645f78-d2ec-11e6-8e20-e3877faaf0bf.png)

**Comment by rjanja** [comment]
1.) This is a bug. I've seen it but haven't addressed it yet. I'd like to redo this screen to make it look a bit cleaner.

2.) The generic settings still exist because they were previously used by my own settings applet (before XletSettings existed). It looks like at least one or two aren't needed anymore, but I haven't removed them yet because I think I'll be moving back to a redesigned settings app.

Generic settings do not require any translations; you are correct they are not displayed.

3.a) "Include applied styles in UI capture"
"Whether to include CSS selection styles in Cinnamon UI screenshots"

When you use the Built-in screenshot and do a UI capture, it applies the CSS class "capture-outline-frame" as you move the mouse over the elements. With this setting turned on, it will capture the styles applied by this CSS. This may be helpful if you're using the screenshot to highlight something in particular (rather than editing it afterwards and drawing a rectangle or circle around it).

3.b) "Capture window as area (suggested, or shots may be black or distorted)"
"Whether to use area selection for window captures"

This is more of a compatibility setting. Asking the desktop manager for a screenshot of a window would usually result in a nice image retaining any transparent regions. But depending on the graphics drivers and Cinnamon version it may sometimes come out black. So the option exists to capture it as a rectangle instead, which isn't nearly as nice but is better than nothing.

The other settings you have mentioned are for the external settings program and can't be set by the user. They were used so that if you had a tab open when you closed the settings, the next time you re-opened the settings it would be at the same tab.

4.) This sounds like a bug in Cinnamon XletSettings. But it may be that tooltip is just not used for button type settings.

**Comment by rjanja** [comment]
I've created two separate tickets for the above problems, it's easier to address them independently.

**Comment by rjanja** [comment]
Thank you for your work in doing the translation to German! Please feel free to open up as many additional issues as you find and I will try to help with the triage.

**Comment by NikoKrause** [comment]
Thanks for answering so fast. 
What about No. 5?
